### ISSUE TITLE
 suggestion of improvement

### ISSUE THREAD

**Issue by llronaldoll** [HBIDamian/TimeCommander#4] opened 2018-08-21 23:21 UTC
make possible the use of selector like the @r and @a used in the playerSelector plugin

example=   give @r diamond 1

**Comment by HBIDamian** [comment] 2018-08-22 04:48
Duplicate of https://github.com/TheDeibo/TimeCommander/issues/3#event-1796016227

**Closed as completed by HBIDamian** 2018-08-22 04:48 UTC
